import DashNav from "@/components/Navbar/DashNav/DashNav";
import "../globals.css";
export const metadata = {
  title: "Kiskfm || Admin Panel",
  description: "Generated by Sifat",
};

export default async function DashboardLayout({ children }) {
  return (
    <body>
      <div style={{ display: "flex", flexDirection: "row", height: "100vh" }}>
        <div>
          <DashNav />
        </div>
        <div
          style={{
            flex: 1,
            overflowY: "auto",
            backgroundImage: "url('https://i.ibb.co/6yd472L/Group-2.png')",
          }}
          className="mt-16 lg:mt-12 px-4 md:px-10"
        >
          {children}
        </div>
      </div>
    </body>
  );
}
