import "../globals.css";
export const metadata = {
  title: "Admin Login",
  description: "Generated by Md abdur rahman sifat",
};

export default function HomeLayout({ children }) {
  return <body className="">{children}</body>;
}
