import "../globals.css";
export const metadata = {
    title: "Admin Login",
    description: "Generated by Md abdur rahman sifat",
  };
  
  export default function RootLayout({ children }) {
    return (
      <html lang="en" data-theme='light'>
        <body className="">
          {children}
        </body>
      </html>
    );
  }